#!/bin/bash
eval "`$(dirname "$0")/sh-init`"

if [[ "x$1" != *".tgz" ]]; then echo "usage: $0 <file.tgz>" 1>&2; exit 1; fi

rm -rf "$1" "$1..dir"
mkdir "$1..dir"
tgt="$(cd "$1..dir"; pwd)"

cd "$(dirname "$COURSE")"
for d in $(find "$(basename "$COURSE")" -name ".git" -type d); do
  if [[ "$d" != "$(basename "$COURSE")/grading/.git" ]]; then
    echo "Extracting $(dirname "$d")"
    cd "$COURSE/../$d/.."
    paths=""
    if [[ -e ".git/info/sparse-checkout" ]]; then
      paths="$(grep . ".git/info/sparse-checkout" | grep -v '^[#!]')"
    fi
    git archive --format="tar" --prefix="$(dirname "$d")/" HEAD $paths | \
      ( cd "$tgt"; tar xf -; )
  fi
done

echo "Packaging into $1"
cd "$tgt"
tar czf "${tgt%..dir}" "$(basename "$COURSE")"
cd "$tgt/.."
rm -rf "$tgt"
